apiVersion: v1
kind: Service
metadata:
  name: serviceapp
  namespace: kube-system
  # namespace: "pie"
spec:
  ports:
    - port: 3000
      targetPort: 80
      protocol: TCP
  selector:
    app: nodeapp
  type: LoadBalancer